site_url: https://sandipsahajoy.xyz/ai4buzz/
site_name: AI4Buzz
theme: readthedocs
nav:
    - Project Requirements: index.md
    - Software Design: design.md
    - Project Management: project-management.md
